# Generated by Django 5.1.7 on 2025-03-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramuser_appr_error_telegramuser_appr_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
