# Generated by Django 5.1.7 on 2025-03-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='appr_error',
            new_name='avg_error',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='appr_time',
            new_name='avg_time',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
