# Generated by Django 5.1.7 on 2025-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_telegramuser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='avg_moves_per_game',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='daily_moves_remaining',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_move_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='total_moves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
