# Generated by Django 5.1.7 on 2025-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_telegramuser_avg_moves_per_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
