# Generated by Django 5.1.7 on 2025-03-13 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='appr_error_dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='closest_guess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closest_guess', to='core.guess'),
        ),
        migrations.AddField(
            model_name='location',
            name='total_guesses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guess',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.location'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
