# Generated by Django 5.1.7 on 2025-03-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='street_view_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_view_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
