# Generated by Django 5.1.7 on 2025-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guess_street_view_url_alter_location_street_view_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guessed_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guessed_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
