# Generated by Django 5.1.7 on 2025-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guess_guessed_lat_alter_guess_guessed_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='appr_error',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='appr_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='total_errors',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
