# Generated by Django 5.1.7 on 2025-03-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_appr_error_location_appr_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='appr_error_dist',
        ),
    ]
