# Generated by Django 5.1.7 on 2025-03-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_location_appr_error_dist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-total_guesses']},
        ),
    ]
