# Generated by Django 5.1.7 on 2025-03-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='street_view_url',
        ),
    ]
