# Generated by Django 5.1.7 on 2025-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_guess_street_view_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guess',
            options={'verbose_name_plural': 'Guesses'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-total_guesses'], 'verbose_name_plural': 'Locations'},
        ),
    ]
