# Generated by Django 5.1.7 on 2025-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rating_remove_location_closest_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
