# Generated by Django 5.1.7 on 2025-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_rating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
