# Generated by Django 5.1.7 on 2025-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_location_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='complexity',
            field=models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='normal', max_length=10),
        ),
    ]
