# Generated by Django 5.1.7 on 2025-04-22 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_location_options_location_complexity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='total_moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guessed_at', models.DateTimeField(auto_now_add=True)),
                ('moves_used', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('guessed_lat', models.FloatField(blank=True, null=True)),
                ('guessed_lng', models.FloatField(blank=True, null=True)),
                ('distance_error', models.FloatField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guesses',
            },
        ),
        migrations.DeleteModel(
            name='Guess',
        ),
    ]
