# Generated by Django 5.1.7 on 2025-04-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'verbose_name_plural': 'Games'},
        ),
    ]
