# Generated by Django 5.1.7 on 2025-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_gameresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
